language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - build-tools-19.1.0
    - build-tools-24.0.2
    - sysimg-19
    - sysimg-24
    - android-19
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
- ./gradlew clean rake:test

after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  slack: skp-di:c0VSovqSCgaZd8qT7cClh799

