language: android

android:
  compoenents:
    - build-tools-19.1.0
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-5be876d5

script:
- gradle :rake:build

after_success:
- gradle cobertura coveralls

notifications:
  slack: skp-di:c0VSovqSCgaZd8qT7cClh799

