language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.2
    - sysimg-28
    - android-28
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
- ./gradlew clean rake:test

after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  slack: skp-di:c0VSovqSCgaZd8qT7cClh799

