language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.1
    - build-tools-26.0.2
    - sysimg-19
    - sysimg-26
    - android-19
    - android-26
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
- ./gradlew clean rake:test

after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  slack: skp-di:c0VSovqSCgaZd8qT7cClh799

