language: android

android:
  components:
    - build-tools-19.1.0
    - build-tools-23.0.0
    - sysimg-19
    - sysimg-23
    - android-19
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
- ./gradlew clean rake:test

after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  slack: skp-di:c0VSovqSCgaZd8qT7cClh799

